import Head from "next/head";
import { useState } from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { CiLight } from "react-icons/ci";
import Footer from "./Footer";
import Landing from "./Landing";
import Services from "./Services";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Ashish Shukla</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white md:px-20 lg:px-40 font-serif tracking-wider dark:bg-gray-900 p-4 lg:p-0">
        <section className="">
          <nav className="lg:py-10 py-4 mb-12 flex space-x-4 lg:space-x-0 justify-between">
            <h1 className=" text-base px-2 font-mono italic uppercase lg:text-2xl cursor-pointer font-base darkModeText hover:text-teal-600 hover:scale-110">
              developedByAS
            </h1>
            <ul className="flex mx-2 items-center">
              <li
                onClick={() => setDarkMode((dark) => !dark)}
                className="cursor-pointer text-2xl lg:hover:scale-125"
              >
                {darkMode ? (
                  <CiLight className="text-white font-bold" />
                ) : (
                  <BsFillMoonStarsFill />
                )}
              </li>
              <li className="hover:scale-110">
                <a
                  target={"_blank"}
                  className=" bg-gradient-to-r cursor-pointer from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="resume1.pdf"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <Landing />
          <section>
            <Services />
          </section>
        </section>
      </main>
      <footer className="">
        <Footer />
      </footer>
    </div>
  );
}
