import Head from "next/head";
import { useState } from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { CiLight } from "react-icons/ci";
import Footer from "./Footer";
import Landing from "./Landing";
import Services from "./Services";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Ashish Shukla</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white md:px-20 lg:px-40 dark:bg-gray-900 p-4 lg:p-0">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-base px-2 font-mono italic uppercase lg:text-2xl darkModeText">
              developedByAS
            </h1>
            <ul className="flex px-3 items-center">
              <li
                onClick={() => setDarkMode(!darkMode)}
                className="cursor-pointer text-2xl"
              >
                {darkMode ? (
                  <CiLight className="text-white font-bold" />
                ) : (
                  <BsFillMoonStarsFill />
                )}
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r cursor-pointer from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <Landing />
          <section>
            <Services />
          </section>
        </section>
      </main>
      <footer className="">
        <Footer />
      </footer>
    </div>
  );
}
